global_config: configs/global.yaml
task: api
host: 0.0.0.0
port: 8000
reload: false
pipeline:
  binary_config: configs/binary.yaml
  landmarks_config: configs/landmarks.yaml
  gallery_config: configs/gallery.yaml
  cascade_path: assets/cascades/haarcascade_frontalcatface.xml
matching:
  top_k: 5
  cosine_threshold: 0.85
  euclidean_threshold: 0.25
